name: Deploy API to S3 (S3 Static Website)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: |
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script. Skipping."
          fi

      - name: Upload build artifact (opcional)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: dist-or-build
          path: |
            dist
            build
          if-no-files-found: ignore

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist s3://cauanecardosoreactproject --delete