name: CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKERHUB_USERNAME: cauhsensei

jobs:
  test:
    name: Tests (Vitest) → Report → Lint → Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      # ---- TESTES PRIMEIRO ----
      - name: Run unit tests (Vitest) + JUnit + GA annotations
        run: |
          mkdir -p reports
          npx vitest run \
            --reporter=default \
            --reporter=github-actions \
            --reporter=junit \
            --outputFile=reports/junit.xml

      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml

      - name: Publish test report to PR Checks
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Vitest Results
          path: reports/junit.xml
          reporter: java-junit
          fail-on-error: true

      # ---- LINT DEPOIS (se quebrar, já publicamos os testes) ----
      - name: Lint (se existir)
        run: |
          if npm run | grep -q "^ *lint"; then
            npm run lint
          else
            echo "No lint script. Skipping."
          fi

      # ---- BUILD OPCIONAL ----
      - name: Build (se existir)
        run: |
          if npm run | grep -q "^ *build"; then
            npm run build
          else
            echo "No build script. Skipping."
          fi

      - name: Upload dist/build (opcional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist-or-build
          path: |
            dist
            build
          if-no-files-found: ignore

  docker:
    name: Docker build & push (só no push na main)
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    env:
      DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        if: ${{ env.DOCKERHUB_PAT != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DO C KERHUB_PAT }}

      - name: Skip push (secret ausente)
        if: ${{ env.DOCKERHUB_PAT == '' }}
        run: echo "DOCKERHUB_PAT ausente. Pulando push para Docker Hub."

      - name: Build & Push
        if: ${{ env.DOCKERHUB_PAT != '' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/login-react-project:latest
            ${{ env.DOCKERHUB_USERNAME }}/login-react-project:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
