name: CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKERHUB_USERNAME: cauhsensei

jobs:
  test:
    name: Testes (Vitest) + Build opcional
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Lint (se existir)
        run: |
          if npm run | grep -q "^ *lint"; then
            npm run lint
          else
            echo "No lint script. Skipping."
          fi

      - name: Testes (Vitest) com JUnit + anotações na PR
        run: |
          mkdir -p reports
          npx vitest run \
            --reporter=default \
            --reporter=github-actions \
            --reporter=junit \
            --outputFile=reports/junit.xml

      - name: Build (se existir)
        run: |
          if npm run | grep -q "^ *build"; then
            npm run build
          else
            echo "No build script. Skipping."
          fi

      - name: Upload artifact - dist/build
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist-or-build
          path: |
            dist
            build
          if-no-files-found: ignore

      - name: Upload artifact - JUnit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml

      - name: Publicar relatório nos Checks da PR
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Vitest Results
          path: reports/junit.xml
          reporter: java-junit
          fail-on-error: true

  docker:
    name: Docker build & push (só no push na main + secret presente)
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.DOCKERHUB_PAT != '' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/login-react-project:latest
            ${{ env.DOCKERHUB_USERNAME }}/login-react-project:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
